kind: Service
apiVersion: v1
metadata:
  name: helm-multi-container-service
spec:
  selector:
    app: label-helm-multi-containers-deployment
  ports:
    - protocol: TCP
      port: {{.Values.helloPort}}
      nodePort: {{.Values.extHelloPort}}
      name: helloport
    - protocol: TCP
      port: {{.Values.app2Port}}
      nodePort: {{.Values.extApp2Port}}
      name: app2port
  type: LoadBalancer
