apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: help-multi-containers-deployment
spec:
  replicas: {{.Values.numReplicas}}
  template:
    metadata:
      labels:
        app: label-helm-multi-containers-deployment
    spec:
      containers:
      - name: hello-container
        image: hello:v1
        ports:
        - containerPort: {{.Values.helloPort}}
      - name: app2-container
        image: app2:v1
        ports:
        - containerPort: {{.Values.app2Port}}
