apiVersion: v2
name: nodeapp-charts
version: 0.1.0
description: My first helm chart for a node JS application
keywords:
  - node docker kubernetes helm tutorial intro
home: https://github.com/thisisdavidbell/node-docker-kubernetes
sources:
  - https://github.com/thisisdavidbell/node-docker-kubernetes
type: application
#engine: gotpl # The name of the template engine (optional, defaults to gotpl)
# icon: A URL to an SVG or PNG image to be used as an icon (optional).
# appVersion: The version of the app that this contains (optional). This needn't be SemVer.
# deprecated: Whether or not this chart is deprecated (optional, boolean)
